apiVersion: apps/v1
kind: Deployment
metadata:
  name: productivity-cal
  labels:
    app: productivity-cal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productivity-cal
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: productivity-cal
    spec:
      containers:
      - name: productivity-cal
        image: 913222011643.dkr.ecr.ap-southeast-1.amazonaws.com/productivity-cal:latest
        imagePullPolicy: Always
        ports:
            - containerPort: 5006
