apiVersion: v1
kind: Service
metadata:
  name: displayresults
spec:
  selector:
    app: displayresults
  type: NodePort
  selector:
    app: displayresults
  ports:
  - protocol: TCP
    nodePort: 30008
    port: 5007
    targetPort: 5007
  type: LoadBalancer
